<?php

namespace Rappasoft\LaravelLivewireTables\Themes;

/**
 * Centralised, per-theme class strings — the first step of the theme-strategy
 * refactor (#23). Blades call `$this->themeClasses('key')` instead of inlining
 * `@if($isTailwind)/@elseif($isBootstrap)` class branches.
 *
 * Keys fall back to the Tailwind theme: the Flux theme is Tailwind-based and only
 * overrides the handful of keys where it differs. Structure (no closures) keeps
 * it config-cache safe. Migrate one blade group at a time, adding its keys here;
 * the tests/Visuals per-theme suite guards that the rendered output is unchanged.
 */
class ThemeStyles
{
    /**
     * @var array<string, array<string, string>>
     */
    protected static array $classes = [
        'tailwind' => [
            'table.wrapper' => 'shadow overflow-y-auto border-b border-gray-200 dark:border-gray-700 sm:rounded-lg',
            'table.element' => 'min-w-full divide-y divide-gray-200 dark:divide-none',
            'table.thead' => 'bg-gray-50 dark:bg-gray-800',
            'table.tbody' => 'bg-white divide-y divide-gray-200 dark:bg-gray-800 dark:divide-none',
            'table.tr.plain' => 'bg-white dark:bg-gray-700 dark:text-white',
            'tools.wrapper' => 'flex-col',
            'toolbar.wrapper' => 'md:flex md:justify-between mb-4 px-4 md:p-0',
            'toolbar.left' => 'w-full mb-4 md:mb-0 md:w-2/4 md:flex space-y-4 md:space-y-0 md:space-x-2',
            'toolbar.right' => 'md:flex md:items-center space-y-4 md:space-y-0 md:space-x-2',
            'toolbar.area' => 'flex rounded-md shadow-sm',
            'th.plain.styling' => 'table-cell px-3 py-2 md:px-6 md:py-3 text-center md:text-left laravel-livewire-tables-reorderingMinimised',
            'th.plain.colors' => 'bg-gray-50 dark:bg-gray-800',
            'th.reorder.styling' => 'table-cell px-6 py-3 text-left text-xs font-medium whitespace-nowrap uppercase tracking-wider',
            'th.reorder.colors' => 'text-gray-500 dark:bg-gray-800 dark:text-gray-400',
            'th.reorder.bs' => '',
            'th.bulkactions.wrapper' => 'inline-flex rounded-md shadow-sm',
            'th.bulkactions.checkbox.colors' => 'border-gray-300 text-indigo-600 focus:border-indigo-300 focus:ring-indigo-200 dark:bg-gray-900 dark:text-white dark:border-gray-600 dark:hover:bg-gray-600 dark:focus:bg-gray-600',
            'th.bulkactions.checkbox.styling' => 'rounded shadow-sm transition duration-150 ease-in-out focus:ring focus:ring-opacity-50 ',
            'th.bulkactions.checkbox.bs' => '',
            'td.bulkactions.wrapper' => 'inline-flex rounded-md shadow-sm',
            'tr.bulkactions.row' => 'bg-indigo-50 dark:bg-gray-900 dark:text-white',
            'tr.bulkactions.btn.styling' => 'ml-1 underline text-sm leading-5 font-medium focus:outline-none focus:underline transition duration-150 ease-in-out',
            'tr.bulkactions.btn.colors' => 'text-blue-600 text-gray-700 focus:text-gray-800 dark:text-white dark:hover:text-gray-400',
            'filter.input.wrapper' => 'rounded-md shadow-sm',
            'filter.input.styling' => 'block w-full rounded-md shadow-sm transition duration-150 ease-in-out focus:ring focus:ring-opacity-50',
            'filter.input.colors' => 'border-gray-300 focus:border-indigo-300 focus:ring-indigo-200 dark:bg-gray-800 dark:text-white dark:border-gray-600',
            'filter.input.bs' => '',
            'filter.select.wrapper' => 'rounded-md shadow-sm',
            'filter.select.styling' => 'block w-full transition duration-150 ease-in-out rounded-md shadow-sm focus:ring focus:ring-opacity-50',
            'filter.numberrange.outer' => 'mt-4 h-22 pt-8 pb-4 grid gap-10',
            'filter.numberrange.slider' => 'range-slider flat',
            'filter.daterange.wrapper' => 'w-full rounded-md shadow-sm text-left ',
            'filter.daterange.input' => 'w-full inline-block align-middle transition duration-150 ease-in-out border-gray-300 rounded-md shadow-sm transition duration-150 ease-in-out focus:border-indigo-300 focus:ring focus:ring-indigo-200/50 dark:bg-gray-800 dark:text-white dark:border-gray-600',
            'toolbar.perpage.margin' => '',
            'toolbar.perpage.styling' => 'block w-full rounded-md shadow-sm transition duration-150 ease-in-out sm:text-sm sm:leading-5 focus:ring focus:ring-opacity-50',
            'toolbar.perpage.colors' => 'border-gray-300 focus:border-indigo-300 focus:ring-indigo-200 dark:bg-gray-700 dark:text-white dark:border-gray-600',
            'td.collapsed.base' => 'p-3 table-cell text-center',
            'td.collapsed.sm' => 'sm:hidden',
            'td.collapsed.md' => 'md:hidden',
            'td.collapsed.lg' => 'lg:hidden',
            'td.collapsed.button' => '',
            'td.collapsed.icon.styling' => 'h-6 w-6',
            'td.collapsed.expandicon.colors' => 'text-green-600',
            'td.collapsed.collapseicon.colors' => 'text-yellow-600',
            'th.collapsed.base' => 'table-cell dark:bg-gray-800 laravel-livewire-tables-reorderingMinimised',
            'collapsed.hiddenclass' => 'hidden',
            'collapsed.tr.even' => 'hidden bg-white dark:bg-gray-700 dark:text-white rappasoft-striped-row',
            'collapsed.tr.odd' => 'hidden bg-gray-50 dark:bg-gray-800 dark:text-white rappasoft-striped-row',
            'collapsed.td' => 'text-left pt-4 pb-2 px-4',
            'collapsed.p.base' => 'block mb-2',
            'collapsed.p.a' => 'sm:block',
            'collapsed.p.b' => 'sm:block md:hidden',
            'collapsed.p.c' => 'sm:block lg:hidden',
            'collapsed.p.d' => '',
            'td.reorder.svg' => 'inline w-4 h-4',
            'toolbar.reorder.margin' => '',
            'toolbar.reorder.button' => 'inline-flex justify-center items-center w-full md:w-auto px-4 py-2 border border-gray-300 shadow-sm text-sm font-medium rounded-md text-gray-700 bg-white hover:text-gray-500 focus:border-indigo-300 focus:ring focus:ring-indigo-200/50 active:bg-gray-50 active:text-gray-800 transition ease-in-out duration-150 dark:bg-gray-700 dark:text-white dark:border-gray-600 dark:hover:bg-gray-600',
            'toolbar.filterbtn.wrapper' => 'relative block md:inline-block text-left',
            'th.sorticons.wrapper' => 'relative flex items-center',
            'filter.multiselect.checkwrapper' => '',
            'filter.multiselect.check.styling' => 'rounded shadow-sm transition duration-150 ease-in-out focus:ring focus:ring-opacity-50 disabled:opacity-50 disabled:cursor-wait',
            'filter.multiselect.check.colors' => 'text-indigo-600 border-gray-300 focus:border-indigo-300  focus:ring-indigo-200  dark:bg-gray-900 dark:text-white dark:border-gray-600 dark:hover:bg-gray-600 dark:focus:bg-gray-600 ',
            'filter.multiselect.label' => 'dark:text-white',
            'td.base' => 'px-6 py-4 whitespace-nowrap text-sm font-medium dark:text-white',
            'td.collapse.always' => 'hidden',
            'td.collapse.mobile' => 'hidden md:table-cell',
            'td.collapse.tablet' => 'hidden lg:table-cell',
            'td.cursor' => '',
            'th.colors' => 'text-gray-500 dark:bg-gray-800 dark:text-gray-400',
            'th.styling' => 'px-6 py-3 text-left text-xs font-medium whitespace-nowrap uppercase tracking-wider',
            'column.boolean.success' => 'inline-block h-5 w-5 text-green-500',
            'column.boolean.danger' => 'inline-block h-5 w-5 text-red-500',
            'filterpills.wrapper' => 'mb-4 px-4 md:p-0',
            'filterpills.small' => 'text-gray-700 dark:text-white',
            'pills.item.styling' => 'inline-flex items-center px-2.5 py-0.5 rounded-full leading-4',
            'pills.item.text' => 'text-xs font-medium capitalize',
            'pills.item.colors' => 'bg-indigo-100 text-indigo-800 dark:bg-indigo-200 dark:text-indigo-900',
            'loading.row' => 'hidden w-full text-center place-items-center align-middle',
            'actions.wrapper' => 'flex flex-cols py-2 space-x-2',
            'fs.container' => '',
            'fs.row' => 'grid grid-cols-12 gap-6 px-4 py-2 mb-2',
            'ba.outer' => 'w-full md:w-auto mb-4 md:mb-0',
            'ba.inner' => 'relative inline-block text-left z-10 w-full md:w-auto',
            'ba.button.bs' => '',
            'ba.button.colors' => 'border-gray-300 bg-white text-gray-700 hover:bg-gray-50 focus:border-indigo-300 focus:ring-indigo-200 dark:bg-gray-700 dark:text-white dark:border-gray-600 dark:hover:bg-gray-600',
            'ba.button.styling' => 'inline-flex justify-center w-full border shadow-sm px-4 py-2 text-sm font-medium focus:ring focus:ring-opacity-50',
            'ba.button.rounded' => 'rounded-md',
            'ba.menu.wrapper.base' => 'origin-top-right absolute right-0 mt-2 w-full md:w-48 shadow-lg bg-white ring-1 divide-y focus:outline-none z-50',
            'ba.menu.wrapper.variant' => 'rounded-md ring-black ring-opacity-5 divide-gray-100',
            'ba.menu.colors' => 'bg-white dark:text-white',
            'ba.menu.colors.variant' => 'dark:bg-gray-700',
            'ba.menu.styling' => 'shadow-xs',
            'ba.menu.rounded' => 'rounded-md',
            'ba.item.colors' => 'text-gray-700 hover:bg-gray-100 hover:text-gray-900 focus:bg-gray-100 focus:text-gray-900 dark:text-white dark:hover:bg-gray-600',
            'ba.item.styling' => 'block w-full px-4 py-2 text-sm leading-5 focus:outline-none flex items-center space-x-2',
            'ba.bsmenu' => '',
            'ba.bsitem' => '',
            'toolbar.filterbtn.button' => 'inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:border-indigo-300 focus:ring focus:ring-indigo-200/50 dark:bg-gray-700 dark:text-white dark:border-gray-600 dark:hover:bg-gray-600',
            'toolbar.filterbtn.badge' => 'ml-1 inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium leading-4 bg-indigo-100 text-indigo-800 capitalize dark:bg-indigo-200 dark:text-indigo-900',
        ],
        'flux' => [
            'ba.button.colors' => 'border-zinc-200 bg-white text-zinc-700 hover:bg-zinc-50 focus:border-zinc-400 focus:ring-zinc-200 dark:bg-zinc-700 dark:text-white dark:border-zinc-600 dark:hover:bg-zinc-600',
            'ba.button.rounded' => 'rounded-lg',
            'ba.menu.wrapper.variant' => 'rounded-lg ring-zinc-950/10 divide-zinc-950/5 dark:ring-white/10 dark:divide-white/10',
            'ba.menu.colors.variant' => 'dark:bg-zinc-700',
            'ba.menu.rounded' => 'rounded-lg',
            'ba.item.colors' => 'text-zinc-700 hover:bg-zinc-100 hover:text-zinc-900 focus:bg-zinc-100 focus:text-zinc-900 dark:text-white dark:hover:bg-zinc-700',
            'table.wrapper' => 'lwt-flux overflow-y-auto',
            'toolbar.filterbtn.button' => 'inline-flex justify-center w-full rounded-lg border border-zinc-200 shadow-sm px-4 py-2 bg-white text-sm font-medium text-zinc-700 hover:bg-zinc-50 focus:border-zinc-400 focus:ring focus:ring-zinc-200/50 dark:bg-zinc-700 dark:text-white dark:border-zinc-600 dark:hover:bg-zinc-600',
            'toolbar.filterbtn.badge' => 'ml-1 inline-flex items-center px-2 py-0.5 rounded-md text-xs font-medium leading-4 bg-zinc-100 text-zinc-700 capitalize dark:bg-zinc-600 dark:text-zinc-100',
        ],
        'bootstrap-4' => [
            'ba.outer' => 'mb-3 mb-md-0',
            'ba.inner' => 'dropdown d-block d-md-inline',
            'ba.button.bs' => 'btn dropdown-toggle d-block d-md-inline',
            'ba.bsmenu' => 'dropdown-menu dropdown-menu-right w-auto',
            'ba.bsitem' => 'dropdown-item',
            'table.wrapper' => 'table-responsive',
            'table.element' => 'laravel-livewire-table table',
            'table.thead' => '',
            'table.tbody' => '',
            'table.tr.plain' => '',
            'tools.wrapper' => 'd-flex flex-column',
            'toolbar.wrapper' => 'd-md-flex justify-content-between mb-3',
            'toolbar.left' => 'd-md-flex',
            'toolbar.right' => 'd-md-flex',
            'toolbar.area' => 'mb-3 mb-md-0 input-group',
            'th.plain.styling' => '',
            'th.plain.colors' => 'laravel-livewire-tables-reorderingMinimised',
            'th.reorder.styling' => '',
            'th.reorder.colors' => '',
            'th.reorder.bs' => 'laravel-livewire-tables-reorderingMinimised',
            'th.bulkactions.wrapper' => 'form-check',
            'th.bulkactions.checkbox.colors' => '',
            'th.bulkactions.checkbox.styling' => '',
            'th.bulkactions.checkbox.bs' => 'form-check-input',
            'td.bulkactions.wrapper' => '',
            'tr.bulkactions.row' => '',
            'tr.bulkactions.btn.styling' => 'btn btn-primary btn-sm',
            'tr.bulkactions.btn.colors' => '',
            'filter.input.wrapper' => 'mb-3 mb-md-0 input-group',
            'filter.input.styling' => '',
            'filter.input.colors' => '',
            'filter.input.bs' => 'form-control',
            'filter.select.wrapper' => 'inline',
            'filter.select.styling' => 'form-control',
            'filter.numberrange.outer' => 'mt-4 h-22 w-100 pb-4 pt-2 grid gap-10',
            'filter.numberrange.slider' => 'range-slider flat w-100',
            'filter.daterange.wrapper' => 'd-inline-block w-100 mb-3 mb-md-0 input-group',
            'filter.daterange.input' => 'd-inline-block w-100 form-control',
            'toolbar.perpage.margin' => 'ml-0 ml-md-2',
            'toolbar.perpage.styling' => 'form-control',
            'toolbar.perpage.colors' => '',
            'td.collapsed.base' => '',
            'td.collapsed.sm' => 'd-sm-none',
            'td.collapsed.md' => 'd-md-none',
            'td.collapsed.lg' => 'd-lg-none',
            'td.collapsed.button' => 'border-0 bg-transparent p-0',
            'td.collapsed.icon.styling' => '',
            'td.collapsed.expandicon.colors' => 'laravel-livewire-tables-btn-lg text-success',
            'td.collapsed.collapseicon.colors' => 'laravel-livewire-tables-btn-lg text-warning',
            'th.collapsed.base' => 'd-table-cell laravel-livewire-tables-reorderingMinimised',
            'collapsed.hiddenclass' => 'd-none',
            'collapsed.tr.even' => 'd-none bg-light rappasoft-striped-row',
            'collapsed.tr.odd' => 'd-none bg-white rappasoft-striped-row',
            'collapsed.td' => 'text-start pt-3 p-2',
            'collapsed.p.base' => 'd-block mb-2',
            'collapsed.p.a' => '',
            'collapsed.p.b' => 'd-md-none',
            'collapsed.p.c' => 'd-lg-none',
            'collapsed.p.d' => 'd-sm-none',
            'td.reorder.svg' => 'd-inline',
            'toolbar.reorder.margin' => 'mr-0 mr-md-2 mb-3 mb-md-0',
            'toolbar.reorder.button' => 'btn btn-default d-block d-md-inline',
            'toolbar.filterbtn.wrapper' => 'btn-group d-block d-md-inline',
            'th.sorticons.wrapper' => 'relative d-flex align-items-center',
            'filter.multiselect.checkwrapper' => 'form-check',
            'filter.multiselect.check.styling' => 'form-check-input',
            'filter.multiselect.check.colors' => '',
            'filter.multiselect.label' => 'form-check-label',
            'td.base' => '',
            'td.collapse.always' => 'd-none',
            'td.collapse.mobile' => 'd-none d-md-table-cell',
            'td.collapse.tablet' => 'd-none d-lg-table-cell',
            'td.cursor' => 'laravel-livewire-tables-cursor',
            'th.colors' => '',
            'th.styling' => '',
            'column.boolean.success' => 'd-inline-block text-success laravel-livewire-tables-btn-small',
            'column.boolean.danger' => 'd-inline-block text-danger laravel-livewire-tables-btn-small',
            'filterpills.wrapper' => 'mb-3',
            'filterpills.small' => '',
            'pills.item.styling' => 'badge badge-pill badge-info d-inline-flex align-items-center',
            'pills.item.text' => '',
            'pills.item.colors' => '',
            'loading.row' => 'd-none w-100 text-center align-items-center',
            'actions.wrapper' => 'd-flex flex-cols py-2 space-x-2',
            'fs.container' => 'container',
            'fs.row' => 'row col-12',
            'toolbar.filterbtn.button' => 'btn dropdown-toggle d-block w-100 d-md-inline',
            'toolbar.filterbtn.badge' => 'badge badge-info',
        ],
        'bootstrap-5' => [
            'ba.outer' => 'mb-3 mb-md-0',
            'ba.inner' => 'dropdown d-block d-md-inline',
            'ba.button.bs' => 'btn dropdown-toggle d-block d-md-inline',
            'ba.bsmenu' => 'dropdown-menu dropdown-menu-end w-auto',
            'ba.bsitem' => 'dropdown-item',
            'table.wrapper' => 'table-responsive',
            'table.element' => 'laravel-livewire-table table',
            'table.thead' => '',
            'table.tbody' => '',
            'table.tr.plain' => '',
            'tools.wrapper' => 'd-flex flex-column',
            'toolbar.wrapper' => 'd-md-flex justify-content-between mb-3',
            'toolbar.left' => 'd-md-flex',
            'toolbar.right' => 'd-md-flex',
            'toolbar.area' => 'mb-3 mb-md-0 input-group',
            'th.plain.styling' => '',
            'th.plain.colors' => 'laravel-livewire-tables-reorderingMinimised',
            'th.reorder.styling' => '',
            'th.reorder.colors' => '',
            'th.reorder.bs' => 'laravel-livewire-tables-reorderingMinimised',
            'th.bulkactions.wrapper' => 'form-check',
            'th.bulkactions.checkbox.colors' => '',
            'th.bulkactions.checkbox.styling' => '',
            'th.bulkactions.checkbox.bs' => 'form-check-input',
            'td.bulkactions.wrapper' => 'form-check',
            'tr.bulkactions.row' => '',
            'tr.bulkactions.btn.styling' => 'btn btn-primary btn-sm',
            'tr.bulkactions.btn.colors' => '',
            'filter.input.wrapper' => 'mb-3 mb-md-0 input-group',
            'filter.input.styling' => '',
            'filter.input.colors' => '',
            'filter.input.bs' => 'form-control',
            'filter.select.wrapper' => 'inline',
            'filter.select.styling' => 'form-select',
            'filter.numberrange.outer' => 'mt-4 h-22 w-100 pb-4 pt-2 grid gap-10',
            'filter.numberrange.slider' => 'range-slider flat w-100',
            'filter.daterange.wrapper' => 'd-inline-block w-100 mb-3 mb-md-0 input-group',
            'filter.daterange.input' => 'd-inline-block w-100 form-control',
            'toolbar.perpage.margin' => 'ms-0 ms-md-2',
            'toolbar.perpage.styling' => 'form-select',
            'toolbar.perpage.colors' => '',
            'td.collapsed.base' => '',
            'td.collapsed.sm' => 'd-sm-none',
            'td.collapsed.md' => 'd-md-none',
            'td.collapsed.lg' => 'd-lg-none',
            'td.collapsed.button' => 'border-0 bg-transparent p-0',
            'td.collapsed.icon.styling' => '',
            'td.collapsed.expandicon.colors' => 'laravel-livewire-tables-btn-lg text-success',
            'td.collapsed.collapseicon.colors' => 'laravel-livewire-tables-btn-lg text-warning',
            'th.collapsed.base' => 'd-table-cell laravel-livewire-tables-reorderingMinimised',
            'collapsed.hiddenclass' => 'd-none',
            'collapsed.tr.even' => 'd-none bg-light rappasoft-striped-row',
            'collapsed.tr.odd' => 'd-none bg-white rappasoft-striped-row',
            'collapsed.td' => 'text-start pt-3 p-2',
            'collapsed.p.base' => 'd-block mb-2',
            'collapsed.p.a' => '',
            'collapsed.p.b' => 'd-md-none',
            'collapsed.p.c' => 'd-lg-none',
            'collapsed.p.d' => 'd-sm-none',
            'td.reorder.svg' => 'd-inline',
            'toolbar.reorder.margin' => 'me-0 me-md-2 mb-3 mb-md-0',
            'toolbar.reorder.button' => 'btn btn-default d-block d-md-inline',
            'toolbar.filterbtn.wrapper' => 'btn-group d-block d-md-inline',
            'th.sorticons.wrapper' => 'relative d-flex align-items-center',
            'filter.multiselect.checkwrapper' => 'form-check',
            'filter.multiselect.check.styling' => 'form-check-input',
            'filter.multiselect.check.colors' => '',
            'filter.multiselect.label' => 'form-check-label',
            'td.base' => '',
            'td.collapse.always' => 'd-none',
            'td.collapse.mobile' => 'd-none d-md-table-cell',
            'td.collapse.tablet' => 'd-none d-lg-table-cell',
            'td.cursor' => 'laravel-livewire-tables-cursor',
            'th.colors' => '',
            'th.styling' => '',
            'column.boolean.success' => 'd-inline-block text-success laravel-livewire-tables-btn-small',
            'column.boolean.danger' => 'd-inline-block text-danger laravel-livewire-tables-btn-small',
            'filterpills.wrapper' => 'mb-3',
            'filterpills.small' => '',
            'pills.item.styling' => 'badge rounded-pill bg-info d-inline-flex align-items-center',
            'pills.item.text' => '',
            'pills.item.colors' => '',
            'loading.row' => 'd-none w-100 text-center align-items-center',
            'actions.wrapper' => 'd-flex flex-cols py-2 space-x-2',
            'fs.container' => 'container',
            'fs.row' => 'row col-12',
            'toolbar.filterbtn.button' => 'btn dropdown-toggle d-block w-100 d-md-inline',
            'toolbar.filterbtn.badge' => 'badge badge-info',
        ],
    ];

    public static function for(string $theme, string $key): string
    {
        return self::$classes[$theme][$key]
            ?? self::$classes['tailwind'][$key]
            ?? '';
    }
}
